sonar.projectKey=farmweather
sonar.projectName=FarmWeather
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.spec.ts

sonar.exclusions=dist/**,coverage/**,node_modules/**,public/**
sonar.coverage.exclusions=src/main.ts,src/**/*.module.ts,src/**/*.dto.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json
sonar.scm.disabled=true
